### ISSUE TITLE
Build k8s_template module

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-collection-k8s#2]
See: https://github.com/ansible/ansible/issues/60134

Basically build a module that makes it simpler to pass in a template (e.g. my-manifest.yml) which can have one or more YAML documents. Parse each document separately, template it via Jinja2, and then pass it to the K8s API as the normal k8s module does...

**Comment by geerlingguy** [comment]
So... the `k8s` modules in ansible do a ton of work via the `k8s` code in core's `lib/module_utils`. I could basically clone all of that into my collection, then work on the required modifications (it looks like it _could_ be as simple as running things through Jinja during `execute_module` within the `KubernetesRawModule` class...), but I left a comment in the Ansible core issue linked in the comment above and would like to see where that leads first.

(Actually... it might be even simpler, I could probably extend `KubernetesRawModule` with `KubernetesTemplateModule` and then override `execute_module` to make it do what I want. Then `import KubernetesRawModule` in the module itself.)

**Comment by geerlingguy** [comment]
I'm actually making a fair bit of progress here... caveats apply of course.

**Comment by geerlingguy** [comment]
So... got far enough for a PoC:

```yaml
- hosts: localhost
  connection: local
  gather_facts: false

  collections:
  - geerlingguy.k8s

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'

  tasks:
    - name: Template a manifest file.
      k8s_template:
        template: manifest.yml.j2
```

However, I've bumped into a wall mentioned by @willthames in the issue linked in the OP; basically, modules _themselves_ cannot access any inventory facts, playbook vars, etc. (I even tried loading them in and you basically get an empty array, even if running on localhost).

According to [this SO answer](https://stackoverflow.com/a/32103731/100134), though, an action plugin could allow a module to execute through it, meaning it _would_ be able to look up vars. So that might be a way to work around this.
