### ISSUE TITLE
Never fail, and after it only do if failed is conflicting!

### ISSUE THREAD

**Issue by misi** [geerlingguy/ansible-collection-k8s#4]
Can you please help! I can't setup dashboard
```
- name: Check if Kubernetes Dashboard UI service already exists.
  shell: kubectl get services --namespace kube-system | grep -q kubernetes-dashboard
  changed_when: false
  **failed_when: false**
  register: kubernetes_dashboard_service
  when: kubernetes_enable_web_ui | bool

- name: Enable the Kubernetes Web Dashboard UI (if configured).
  command: "kubectl create -f {{ kubernetes_web_ui_manifest_file }}"
  when:
    - kubernetes_enable_web_ui | bool
    - **kubernetes_dashboard_service is failed**
```
The output if I run is the following
```
TASK [geerlingguy.kubernetes : Check if Kubernetes Dashboard UI service already exists.] **************************************************************************************************************************************************************************************
ok: [193.224.23.11]

TASK [geerlingguy.kubernetes : Enable the Kubernetes Web Dashboard UI (if configured).] ***************************************************************************************************************************************************************************************
skipping: [193.224.23.11]
```
If I run the command it fails, only the `failed_when: false` override it
```
$ ansible -i hosts -b -u debian k8s-1 -m shell -a "kubectl get services --namespace kube-system | grep -q kubernetes-dashboard"

193.224.23.11 | FAILED | rc=1 >>
non-zero return code

$ 
```
Any hint would be appreciated!
Thanks!
