### ISSUE TITLE
Add `k8s_wait` module

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-collection-k8s#5]
Just wanted to throw this out here, since it's something that would be convenient in a number of circumstances.

A common pattern for K8s deployments is:

  1. Apply a manifest to create a new Deployment.
  2. Wait for all the Pods in this Deployment to be Ready.
  3. Do other stuff.

Currently, for number 2, you can futz around with the returned data from `k8s` or `k8s_info` and use until/retries to get something working, or you can do a more simple method (if you have `kubectl` available) using `kubectl wait`:

    kubectl wait --for=condition=Ready pods --selector app=my-app-name --timeout=60s

At a basic level, I'd want something like:

```yaml
- name: Wait for my-app-name pods to be ready.
  k8s_wait:
    for: condition=Ready
    type: pods
    selector:
      - app=my-app-name
    timeout: 60s
```

Something along those lines... not sure. But it would be nice to be able to specify this in a more structured way, and not have to rely on `kubectl` being present for a task like:

```yaml
- name: Wait for my-app-name pods to be ready.
  command: >
    kubectl wait --for=condition=Ready
    pods --selector app=my-app-name --timeout=60s
  changed_when: false
```
